export const usStates = [
  { abbreviation: 'AL', name: 'Alabama' },
  { abbreviation: 'AK', name: 'Alaska' },
  { abbreviation: 'AS', name: 'American Samoa' },
  { abbreviation: 'AZ', name: 'Arizona' },
  { abbreviation: 'AR', name: 'Arkansas' },
  { abbreviation: 'CA', name: 'California' },
  { abbreviation: 'CO', name: 'Colorado' },
  { abbreviation: 'CT', name: 'Connecticut' },
  { abbreviation: 'DE', name: 'Delaware' },
  { abbreviation: 'DC', name: 'District Of Columbia' },
  { abbreviation: 'FM', name: 'Federated States Of Micronesia' },
  { abbreviation: 'FL', name: 'Florida' },
  { abbreviation: 'GA', name: 'Georgia' },
  { abbreviation: 'GU', name: 'Guam' },
  { abbreviation: 'HI', name: 'Hawaii' },
  { abbreviation: 'ID', name: 'Idaho' },
  { abbreviation: 'IL', name: 'Illinois' },
  { abbreviation: 'IN', name: 'Indiana' },
  { abbreviation: 'IA', name: 'Iowa' },
  { abbreviation: 'KS', name: 'Kansas' },
  { abbreviation: 'KY', name: 'Kentucky' },
  { abbreviation: 'LA', name: 'Louisiana' },
  { abbreviation: 'ME', name: 'Maine' },
  { abbreviation: 'MH', name: 'Marshall Islands' },
  { abbreviation: 'MD', name: 'Maryland' },
  { abbreviation: 'MA', name: 'Massachusetts' },
  { abbreviation: 'MI', name: 'Michigan' },
  { abbreviation: 'MN', name: 'Minnesota' },
  { abbreviation: 'MS', name: 'Mississippi' },
  { abbreviation: 'MO', name: 'Missouri' },
  { abbreviation: 'MT', name: 'Montana' },
  { abbreviation: 'NE', name: 'Nebraska' },
  { abbreviation: 'NV', name: 'Nevada' },
  { abbreviation: 'NH', name: 'New Hampshire' },
  { abbreviation: 'NJ', name: 'New Jersey' },
  { abbreviation: 'NM', name: 'New Mexico' },
  { abbreviation: 'NY', name: 'New York' },
  { abbreviation: 'NC', name: 'North Carolina' },
  { abbreviation: 'ND', name: 'North Dakota' },
  { abbreviation: 'MP', name: 'Northern Mariana Islands' },
  { abbreviation: 'OH', name: 'Ohio' },
  { abbreviation: 'OK', name: 'Oklahoma' },
  { abbreviation: 'OR', name: 'Oregon' },
  { abbreviation: 'PW', name: 'Palau' },
  { abbreviation: 'PA', name: 'Pennsylvania' },
  { abbreviation: 'PR', name: 'Puerto Rico' },
  { abbreviation: 'RI', name: 'Rhode Island' },
  { abbreviation: 'SC', name: 'South Carolina' },
  { abbreviation: 'SD', name: 'South Dakota' },
  { abbreviation: 'TN', name: 'Tennessee' },
  { abbreviation: 'TX', name: 'Texas' },
  { abbreviation: 'UT', name: 'Utah' },
  { abbreviation: 'VT', name: 'Vermont' },
  { abbreviation: 'VI', name: 'Virgin Islands' },
  { abbreviation: 'VA', name: 'Virginia' },
  { abbreviation: 'WA', name: 'Washington' },
  { abbreviation: 'WV', name: 'West Virginia' },
  { abbreviation: 'WI', name: 'Wisconsin' },
  { abbreviation: 'WY', name: 'Wyoming' },
];

export const mexicoStates = [
  { abbreviation: 'AG', name: 'Aguascalientes' },
  { abbreviation: 'BC', name: 'Baja California' },
  { abbreviation: 'BS', name: 'Baja California Sur' },
  { abbreviation: 'CH', name: 'Chihuahua' },
  { abbreviation: 'CL', name: 'Colima' },
  { abbreviation: 'CM', name: 'Campeche' },
  { abbreviation: 'CO', name: 'Coahuila' },
  { abbreviation: 'CS', name: 'Chiapas' },
  { abbreviation: 'DF', name: 'Federal District' },
  { abbreviation: 'DG', name: 'Durango' },
  { abbreviation: 'GR', name: 'Guerrero' },
  { abbreviation: 'GT', name: 'Guanajuato' },
  { abbreviation: 'HG', name: 'Hidalgo' },
  { abbreviation: 'JA', name: 'Jalisco' },
  { abbreviation: 'ME', name: 'México State' },
  { abbreviation: 'MI', name: 'Michoacán' },
  { abbreviation: 'MO', name: 'Morelos' },
  { abbreviation: 'NA', name: 'Nayarit' },
  { abbreviation: 'NL', name: 'Nuevo León' },
  { abbreviation: 'OA', name: 'Oaxaca' },
  { abbreviation: 'PB', name: 'Puebla' },
  { abbreviation: 'QE', name: 'Querétaro' },
  { abbreviation: 'QR', name: 'Quintana Roo' },
  { abbreviation: 'SI', name: 'Sinaloa' },
  { abbreviation: 'SL', name: 'San Luis Potosí' },
  { abbreviation: 'SO', name: 'Sonora' },
  { abbreviation: 'TB', name: 'Tabasco' },
  { abbreviation: 'TL', name: 'Tlaxcala' },
  { abbreviation: 'TM', name: 'Tamaulipas' },
  { abbreviation: 'VE', name: 'Veracruz' },
  { abbreviation: 'YU', name: 'Yucatán' },
  { abbreviation: 'ZA', name: 'Zacatecas' },
];

export const canadaProvinces = [
  { abbreviation: 'AB', name: 'Alberta' },
  { abbreviation: 'BC', name: 'British Columbia' },
  { abbreviation: 'MB', name: 'Manitoba' },
  { abbreviation: 'NB', name: 'New Brunswick' },
  { abbreviation: 'NL', name: 'Newfoundland and Labrador' },
  { abbreviation: 'NT', name: 'Northwest Territories' },
  { abbreviation: 'NS', name: 'Nova Scotia' },
  { abbreviation: 'NU', name: 'Nunavut' },
  { abbreviation: 'ON', name: 'Ontario' },
  { abbreviation: 'PE', name: 'Prince Edward Island' },
  { abbreviation: 'QC', name: 'Quebec' },
  { abbreviation: 'SK', name: 'Saskatchewan' },
  { abbreviation: 'YT', name: 'Yukon Territory' },
];

export const countries = [
  {
    abbreviation: 'US',
    name: 'United States',
  },
  {
    abbreviation: 'CA',
    name: 'Canada',
  },
  {
    abbreviation: 'MX',
    name: 'Mexico',
  },
];

export const provinces = {
  CA: canadaProvinces,
  MX: mexicoStates,
  US: usStates,
};
